#!/usr/bin/env bash
set -eo pipefail

if [[ -f "${HOME}/.zshrc" ]]; then
  echo "${HOME}/.zshrc alread exists"
else
  ln -s "${HOME}/.dotfiles/zsh/.zshrc" "${HOME}/.zshrc"
fi

touch "${HOME}/.zsh_local"
touch "${HOME}/.local_functions"
touch "${HOME}/.zsh_plugins_local"

#Set up Powerlevel10k
git clone git@github.com:romkatv/powerlevel10k.git\
  "./zsh/oh-my-zsh/custom/themes/powerlevel10k"

#Set up nvim
sh -c 'curl -fLo \
  "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim \
  --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

#Install plugins
nvim -c :PlugInstall
