#!/usr/bin/env bash
set -eo pipefail

ln -s "${HOME}/.dotfiles/zsh/.zshrc" "${HOME}/.zshrc"
touch "${HOME}/.zsh_local"
touch "${HOME}/.local_functions"
touch "${HOME}/.zsh_plugins_local"

#Set up Powerlevel10k
git clone git@github.com:romkatv/powerlevel10k.git "./zsh/oh-my-zsh/custom/themes/"

#Set up nvim
sh -c 'curl -fLo \
  "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim \
  --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

#Install plugins
vim -c :PlugInstall
